# Generated by Django 4.2 on 2026-06-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0012_session_rpe_help_text_acwr_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist'), ('system', 'System')], default='patient', max_length=10)),
                ('change_type', models.CharField(choices=[('flags_updated', 'Flags updated'), ('absolute_stop_set', 'Absolute stop set'), ('absolute_stop_cleared', 'Absolute stop cleared')], max_length=25)),
                ('old_flags', models.JSONField(blank=True, default=list)),
                ('new_flags', models.JSONField(blank=True, default=list)),
                ('old_stop', models.BooleanField(default=False)),
                ('new_stop', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flag_events', to='strength_app.patientprofile')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
