# Generated by Django 4.2 on 2026-06-11 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0017_exerciseexecution_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseexecution',
            name='prescribed_reps',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exerciseexecution',
            name='prescribed_sets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories_per_100g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbs_per_100g',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat_per_100g',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein_per_100g',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gatetestresult',
            name='depth_achieved',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='xp_earned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='dailyfoodlog',
            index=models.Index(fields=['patient', 'log_date'], name='strength_ap_patient_63d473_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['patient', 'session_date'], name='strength_ap_patient_b6cdc4_idx'),
        ),
    ]
