# Generated by Django 4.2 on 2026-06-11 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0018_validators_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseexecution',
            name='pain_action',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exerciseexecution',
            name='pain_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exerciseexecution',
            name='pain_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciseexecution',
            name='pain_severity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='exerciseexecution',
            name='pain_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exerciseexecution',
            name='skip_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exerciseexecution',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
