# Generated by Django 4.2 on 2026-06-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0019_exerciseexecution_pain_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseexecution',
            name='overall_form_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseexecution',
            name='rep_quality_source',
            field=models.CharField(choices=[('cv', 'CV-classified per rep'), ('derived', 'Estimated from form score'), ('manual', 'Self-counted, no form tracking')], default='derived', max_length=10),
        ),
    ]
