# Generated by Django 4.2.30 on 2026-06-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0021_patientprofile_must_change_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(blank=True, default='', max_length=100)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=200)),
                ('context', models.CharField(choices=[('between_sets', 'Between sets'), ('between_exercises', 'Between exercises')], default='between_sets', max_length=20)),
                ('extra_seconds', models.PositiveSmallIntegerField(default=0)),
                ('cut_short', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_events', to='strength_app.patientprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_events', to='strength_app.workoutsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(blank=True, default='', max_length=100)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=200)),
                ('set_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rep_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_type', models.CharField(blank=True, default='', max_length=20)),
                ('pain_severity', models.PositiveSmallIntegerField(default=0)),
                ('threshold_applied', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('continued', 'Continued exercise'), ('exercise_skipped', 'Exercise skipped'), ('session_paused', 'Whole session paused')], default='continued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_events', to='strength_app.patientprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_events', to='strength_app.workoutsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
