# Generated by Django 4.2 on 2026-06-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_app', '0003_add_phone_to_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='therapist_app.therapistpatientlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('pain', 'Sharp / high pain during session'), ('red_flag', 'Red-flag change'), ('missed', 'Missed sessions'), ('other', 'Other')], default='other', max_length=12)),
                ('message', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='therapist_app.therapistpatientlink')),
            ],
            options={
                'ordering': ['is_reviewed', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['link', 'is_reviewed'], name='therapist_a_link_id_abd7de_idx'),
        ),
    ]
