# Generated by Django 4.2.30 on 2026-06-25 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strength_app', '0022_restevent_painevent'),
        ('therapist_app', '0004_visitnote_alert_alert_therapist_a_link_id_abd7de_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='pain_stop_threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='therapistmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TherapistActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reduced_sets', 'Reduced sets'), ('reduced_reps', 'Reduced reps'), ('reduced_load', 'Reduced load'), ('changed_threshold', 'Changed pain threshold'), ('message', 'Sent message'), ('no_change', 'No change')], max_length=20)),
                ('old_value', models.CharField(blank=True, default='', max_length=80)),
                ('new_value', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='therapist_app.therapistpatientlink')),
                ('pain_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_actions', to='strength_app.painevent')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='therapist_app.prescriptionitem')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
