# Generated by Django 4.2.30 on 2026-07-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0023_restevent_session_log_restevent_set_number_and_more'),
        ('therapist_app', '0006_sessionlogitem_started_at_exercisesetlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('complete', 'Completed'), ('ended_early_pain', 'Ended early — pain'), ('partial', 'Partial')], default='complete', max_length=20)),
                ('report_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='therapist_app.therapistpatientlink')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='strength_app.patientprofile')),
                ('session_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='therapist_app.sessionlog')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'report_date'], name='therapist_a_patient_95207d_idx')],
            },
        ),
    ]
