"""
R2-W1: server-side access to the generated CV-targets artifact.

exercise_targets.json is generated by `manage.py export_exercise_targets`
from the Python exercise-module registry (the single source of truth for
phases/targets) plus the audited js_type/tracking table. Execute views
embed the current exercise's entry via json_script so the client JS never
needs its own hardcoded copy of the mapping.

An exercise with no entry runs in MANUAL mode — the safe default: we never
fake camera tracking for an unknown exercise.
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_TARGETS_PATH = (
    Path(__file__).resolve().parent
    / 'static' / 'strength_app' / 'js' / 'exercise_targets.json'
)

_cache = None


def _load():
    global _cache
    if _cache is None:
        try:
            with open(_TARGETS_PATH) as fh:
                _cache = json.load(fh)
        except (OSError, ValueError) as exc:
            logger.error("exercise_targets.json unreadable (%s) — all exercises "
                         "will run in manual mode", exc)
            _cache = {}
    return _cache


def get_cv_config(exercise_id):
    """Return the CV config dict for an exercise, or a manual-mode stub."""
    entry = _load().get(exercise_id or '')
    if entry:
        return entry
    return {
        'display_name': (exercise_id or '').replace('_', ' ').title(),
        'unilateral': False,
        'movement_pattern': '',
        'is_hold': False,
        'tracking': 'manual',
        'js_type': None,
        'phases': {},
    }


_VIDEOS_DIR = (
    Path(__file__).resolve().parent / 'static' / 'strength_app' / 'videos'
)
_videos_cache = None


def get_video_mode_exercises():
    """2026-07 Phase 4: engine keys with a filmed reference video on disk.
    Drop <engine_key>.mp4 into static/strength_app/videos/ (+ collectstatic)
    and that exercise runs VIDEO_MODE on the next process start — no code
    edit. Replaces the old hardcoded VIDEO_MODE_EXERCISES allowlist in
    v1_exercise_execute.html."""
    global _videos_cache
    if _videos_cache is None:
        try:
            _videos_cache = sorted(p.stem for p in _VIDEOS_DIR.glob('*.mp4'))
        except OSError as exc:
            logger.error('videos dir unreadable (%s) — VIDEO_MODE disabled', exc)
            _videos_cache = []
    return list(_videos_cache)
